export { withImmute } from 'domain-objects';

export * from '@src/domain.objects';
export { genActor } from '@src/domain.operations/actor/genActor';
export { castBriefsToPrompt } from '@src/domain.operations/briefs/castBriefsToPrompt';
export { genContextBrain } from '@src/domain.operations/context/genContextBrain';
export { genContextStitchTrail } from '@src/domain.operations/context/genContextStitchTrail';
export { enrollThread } from '@src/domain.operations/role/enrollThread';
export { genRoleSkill } from '@src/domain.operations/role/genRoleSkill';
export { getRoleBriefs } from '@src/domain.operations/role/getRoleBriefs';
export type { ContextStitchTrail } from '@src/domain.operations/stitch/withStitchTrail';
export { genStepImagineViaTemplate } from '@src/domain.operations/template/genStepImagineViaTemplate';
export { genTemplate } from '@src/domain.operations/template/genTemplate';
export { getTemplatePathByCallerPath } from '@src/domain.operations/template/getTemplatePathByCallerPath';
export { getTemplateValFromArtifacts } from '@src/domain.operations/template/getTemplateValFromArtifacts';
export { getTemplateVarsFromRoleInherit } from '@src/domain.operations/template/getTemplateVarsFromInheritance';
export { useTemplate } from '@src/domain.operations/template/useTemplate';
export { getStitch } from '@src/domain.operations/thread/getStitch';
export { asStitcher } from '@src/domain.operations/weave/compose/asStitcher';
export { asStitcherFlat } from '@src/domain.operations/weave/compose/asStitcherFlat';
export { genStitchChoice } from '@src/domain.operations/weave/compose/genStitchChoice';
export { genStitchCycle } from '@src/domain.operations/weave/compose/genStitchCycle';
export { genStitchFanout } from '@src/domain.operations/weave/compose/genStitchFanout';
export { genStitchRoute } from '@src/domain.operations/weave/compose/genStitchRoute';
export { enweaveOneStitcher } from '@src/domain.operations/weave/enweaveOneStitcher';
